# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 5 * * 1'
    - cron:  '15 5 * * 2'
    - cron:  '20 5 * * 3'
    - cron:  '24 5 * * 4'
    - cron:  '30 5 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: |
          touch .env
          echo USER_TOKEN=${{ secrets.USER_TOKEN }} >> .env
          echo CHANNEL_ID=${{ secrets.CHANNEL_ID_PROD }} >> .env
      - run: npm ci
      - run: npm run build --if-present
      - run: NODE_ENV=production node build/index.js
